apiVersion: metakube.syseleven.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: metakube-creds
      namespace: crossplane-system
      key: token
