apiVersion: platform.example.com/v1alpha1
kind: MetaKubeCluster
metadata:
  name: my-test-cluster
  namespace: default
spec:
  parameters:
    projectId: "YOUR_PROJECT_ID_HERE"  # Replace with your MetaKube project ID
    dcName: syseleven-dus2
    kubernetesVersion: "1.34.1"
    cloudProvider: openstack
    nodeCount: 2
    nodeSize: m1.small
    nodeImage: "Ubuntu 22.04"
  compositionSelector:
    matchLabels:
      provider: syseleven
      cloudProvider: openstack
