// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type BindingInitParameters struct {

	// (String) The id of the cluster resource belongs to
	// The id of the cluster resource belongs to
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The name of the namespace
	// The name of the namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The id of the project resource belongs to
	// The id of the project resource belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The name of the role to bind to
	// The name of the role to bind to
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// Users and groups to bind for
	Subject []SubjectInitParameters `json:"subject,omitempty" tf:"subject,omitempty"`
}

type BindingObservation struct {

	// (String) The id of the cluster resource belongs to
	// The id of the cluster resource belongs to
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the namespace
	// The name of the namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The id of the project resource belongs to
	// The id of the project resource belongs to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The name of the role to bind to
	// The name of the role to bind to
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// Users and groups to bind for
	Subject []SubjectObservation `json:"subject,omitempty" tf:"subject,omitempty"`
}

type BindingParameters struct {

	// (String) The id of the cluster resource belongs to
	// The id of the cluster resource belongs to
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The name of the namespace
	// The name of the namespace
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The id of the project resource belongs to
	// The id of the project resource belongs to
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The name of the role to bind to
	// The name of the role to bind to
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// Users and groups to bind for
	// +kubebuilder:validation:Optional
	Subject []SubjectParameters `json:"subject,omitempty" tf:"subject,omitempty"`
}

type SubjectInitParameters struct {

	// (String) Can be either 'user' or 'group'
	// Can be either 'user' or 'group'
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Subject name
	// Subject name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SubjectObservation struct {

	// (String) Can be either 'user' or 'group'
	// Can be either 'user' or 'group'
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Subject name
	// Subject name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SubjectParameters struct {

	// (String) Can be either 'user' or 'group'
	// Can be either 'user' or 'group'
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind" tf:"kind,omitempty"`

	// (String) Subject name
	// Subject name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// BindingSpec defines the desired state of Binding
type BindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BindingInitParameters `json:"initProvider,omitempty"`
}

// BindingStatus defines the observed state of Binding.
type BindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Binding is the Schema for the Bindings API. Role binding allows binding roles to users and groups in a namespace
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,syseleven-metakube}
type Binding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleName) || (has(self.initProvider) && has(self.initProvider.roleName))",message="spec.forProvider.roleName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subject) || (has(self.initProvider) && has(self.initProvider.subject))",message="spec.forProvider.subject is a required parameter"
	Spec   BindingSpec   `json:"spec"`
	Status BindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BindingList contains a list of Bindings
type BindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Binding `json:"items"`
}

// Repository type metadata.
var (
	Binding_Kind             = "Binding"
	Binding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Binding_Kind}.String()
	Binding_KindAPIVersion   = Binding_Kind + "." + CRDGroupVersion.String()
	Binding_GroupVersionKind = CRDGroupVersion.WithKind(Binding_Kind)
)

func init() {
	SchemeBuilder.Register(&Binding{}, &BindingList{})
}
