name: Tag

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  tag:
    uses: crossplane-contrib/provider-workflows/.github/workflows/tag.yml
    with:
      version: ${{ github.event.inputs.version }}
      message: ${{ github.event.inputs.message }}
